version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - rag_network

  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    environment:
      - DATABASE_URL=mysql+pymysql://username:password@host.docker.internal/backup
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - rag_network

volumes:
  es_data:
    driver: local

networks:
  rag_network:
    driver: bridge
